# Generated by Django 2.1.15 on 2020-02-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='zip',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
