# Generated by Django 2.1.15 on 2020-02-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200226_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='contact_number',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
